apply plugin: 'java-library'
apply plugin: 'org.jetbrains.kotlin.jvm'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
kotlin {
    compilerOptions { jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17) }
}

dependencies {
    api project(':shared')
    api "com.badlogicgames.gdx:gdx:$gdxVersion"
    api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
    api "org.java-websocket:Java-WebSocket:$wsVersion"
    api 'org.slf4j:slf4j-nop:2.0.13'
}
